import dynamic from "next/dynamic";
import Head from "next/head";
import CustomScroll from "react-custom-scroll";
import styles from "../styles/Home.module.css";
import { Hero } from "../src/components/Hero";
import { Navbar } from "../src/components/Navbar";
import { useState } from "react";
import { Box, Link, Text, chakra } from "@chakra-ui/react";

const About = dynamic(() =>
  import("../src/components/About").then((mod) => mod.About)
);

const Features = dynamic(() =>
  import("../src/components/Features").then((mod) => mod.Features)
);

const Screenshots = dynamic(() =>
  import("../src/components/Screenshots").then((mod) => mod.Screenshots)
);

export default function Home() {
  const [headerBg, setHeaderBg] = useState("transparent");

  const changeNavbarBg = (value) => {
    if (value > 100) {
      setHeaderBg("rgb(0,0,0,0.9)");
    } else {
      setHeaderBg("transparent");
    }
  };

  return (
    <Box h="100vh">
      <CustomScroll
        onScroll={(e) => changeNavbarBg(e.target.scrollTop)}
        heightRelativeToParent="100%"
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <chakra.header position="relative">
          <Navbar headerBg={headerBg} />
        </chakra.header>
        <main>
          <Hero />
          <About />
          <Features />
          <Screenshots />
        </main>

        <Box bg="gray.800" px={[2, , 8]}>
          <footer className={styles.footer}>
            <Text color="gray.400" fontSize={["xs", , "sm", "md"]}>
              © 2021 Safe Event Planner. All rights reserved.
              <Link
                color="blue.500"
                href="https://safe-event-planner-api.herokuapp.com/privacy-policy"
                isExternal
                ml={2}
              >
                Privacy Policy
              </Link>
            </Text>
          </footer>
        </Box>
      </CustomScroll>
      {/*language=CSS*/}
      <style jsx global>
        {`
          .rcs-inner-handle {
            background-color: #cccccc !important;
          }
        `}
      </style>
    </Box>
  );
}
