import Head from "next/head";
import { Hero } from "../src/components/Hero";
import { Navbar } from "../src/components/Navbar";
import styles from "../styles/Home.module.css";
import PerfectScrollbar from "react-perfect-scrollbar";
import { useRef } from "react";
import { About } from "../src/components/about";
import { Features } from "../src/components/Features";

export default function Home() {
  const containerRef = useRef(null);

  return (
    <PerfectScrollbar
      containerRef={(ref) => (containerRef.current = ref)}
      style={{ height: "100vh" }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <header>
        <Navbar containerRef={containerRef} />
      </header>

      <main>
        <Hero />
        <About />
        <Features />
      </main>

      <footer className={styles.footer}>
        © 2021 Safe Event Planner. All rights reserved.
      </footer>
    </PerfectScrollbar>
  );
}
